version: '2.1'

services:
  eureka-sv:
    build: eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'tiendaelectronicanetwork'
  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "443:443"
    networks:
      - 'tiendaelectronicanetwork'
  products:
    build: products
    mem_limit: 512m
    ports:
      - "8094:8094"
    environment:
      DB_URL: jdbc:mysql://service_products_bd:3306/service_products?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: admin
    restart: always
    depends_on:
      service_products_bd:
          condition: service_healthy
  service_products_bd:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: service_products
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - 'tiendaelectronicanetwork'
  shoppingcart:
    build: shoppingcart
    mem_limit: 512m
    ports:
      - "8092:8092"
    environment:
      DB_URL: jdbc:mysql://service_shoppingcart_bd:3308/service_shoppingcart?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: admin
    restart: always
    depends_on:
      service_shoppingcart_bd:
          condition: service_healthy
  service_shoppingcart_bd:
    image: mysql:8.0.33 
    ports:
      - "3309:3308"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: service_shoppingcart
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - 'tiendaelectronicanetwork'
  sales:
    build: sales
    mem_limit: 512m
    ports:
      - "8093:8093"
    environment:
      DB_URL: jdbc:mysql://service_sales_bd:3310/service_sales?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: admin
    restart: always
    depends_on:
      service_sales_bd:
          condition: service_healthy
  service_sales_bd:
    image: mysql:8.0.33 
    ports:
      - "3311:3310"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: service_sales
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - 'tiendaelectronicanetwork'
  config-server:
    build: config-server
    mem_limit: 512m
    ports:
      - "8081:8081"
    networks:
      - 'tiendaelectronicanetwork'

networks:
  tiendaelectronicanetwork: