spring:
  application:
    name: products

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://service_products_bd:3306/service_products?serverTimezone=UTC
    username: root
    password: admin

server:
  port: 8094

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka