spring:
  application:
    name: sales

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://service_sales_bd:3306/service_sales?serverTimezone=UTC
    username: root
    password: admin

server:
  port: 8093

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka